name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  test-ubuntu:
    name: "test on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Poetry
        run: pipx install git+https://github.com/python-poetry/poetry.git@dca6ff2699a06c0217ed6d5a278fa3146e4136ff
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install Chirp and its dependencies
        run: |
          sudo apt-get install libsndfile1
          poetry install
      - name: Test with unittest
        run: poetry run python -m unittest discover -s chirp/tests -p "*test.py"
